"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HopMessage(_message.Message):
    """Circuit v2 message types"""

    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HopMessage._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        RESERVE: HopMessage._Type.ValueType  # 0
        CONNECT: HopMessage._Type.ValueType  # 1
        STATUS: HopMessage._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    RESERVE: HopMessage.Type.ValueType  # 0
    CONNECT: HopMessage.Type.ValueType  # 1
    STATUS: HopMessage.Type.ValueType  # 2

    TYPE_FIELD_NUMBER: _builtins.int
    PEER_FIELD_NUMBER: _builtins.int
    RESERVATION_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SENDERRECORD_FIELD_NUMBER: _builtins.int
    type: Global___HopMessage.Type.ValueType
    peer: _builtins.bytes
    senderRecord: _builtins.bytes
    """Envelope(PeerRecord)"""
    @_builtins.property
    def reservation(self) -> Global___Reservation: ...
    @_builtins.property
    def limit(self) -> Global___Limit: ...
    @_builtins.property
    def status(self) -> Global___Status: ...
    def __init__(
        self,
        *,
        type: Global___HopMessage.Type.ValueType = ...,
        peer: _builtins.bytes = ...,
        reservation: Global___Reservation | None = ...,
        limit: Global___Limit | None = ...,
        status: Global___Status | None = ...,
        senderRecord: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_senderRecord", b"_senderRecord", "limit", b"limit", "reservation", b"reservation", "senderRecord", b"senderRecord", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_senderRecord", b"_senderRecord", "limit", b"limit", "peer", b"peer", "reservation", b"reservation", "senderRecord", b"senderRecord", "status", b"status", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__senderRecord: _TypeAlias = _typing.Literal["senderRecord"]  # noqa: Y015
    _WhichOneofArgType__senderRecord: _TypeAlias = _typing.Literal["_senderRecord", b"_senderRecord"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__senderRecord) -> _WhichOneofReturnType__senderRecord | None: ...

Global___HopMessage: _TypeAlias = HopMessage  # noqa: Y015

@_typing.final
class StopMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StopMessage._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        CONNECT: StopMessage._Type.ValueType  # 0
        STATUS: StopMessage._Type.ValueType  # 1

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    CONNECT: StopMessage.Type.ValueType  # 0
    STATUS: StopMessage.Type.ValueType  # 1

    TYPE_FIELD_NUMBER: _builtins.int
    PEER_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SENDERRECORD_FIELD_NUMBER: _builtins.int
    type: Global___StopMessage.Type.ValueType
    peer: _builtins.bytes
    senderRecord: _builtins.bytes
    """Envelope(PeerRecord) encoded"""
    @_builtins.property
    def status(self) -> Global___Status: ...
    def __init__(
        self,
        *,
        type: Global___StopMessage.Type.ValueType = ...,
        peer: _builtins.bytes = ...,
        status: Global___Status | None = ...,
        senderRecord: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_senderRecord", b"_senderRecord", "senderRecord", b"senderRecord", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_senderRecord", b"_senderRecord", "peer", b"peer", "senderRecord", b"senderRecord", "status", b"status", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__senderRecord: _TypeAlias = _typing.Literal["senderRecord"]  # noqa: Y015
    _WhichOneofArgType__senderRecord: _TypeAlias = _typing.Literal["_senderRecord", b"_senderRecord"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__senderRecord) -> _WhichOneofReturnType__senderRecord | None: ...

Global___StopMessage: _TypeAlias = StopMessage  # noqa: Y015

@_typing.final
class Reservation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOUCHER_FIELD_NUMBER: _builtins.int
    SIGNATURE_FIELD_NUMBER: _builtins.int
    EXPIRE_FIELD_NUMBER: _builtins.int
    voucher: _builtins.bytes
    signature: _builtins.bytes
    expire: _builtins.int
    def __init__(
        self,
        *,
        voucher: _builtins.bytes = ...,
        signature: _builtins.bytes = ...,
        expire: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expire", b"expire", "signature", b"signature", "voucher", b"voucher"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Reservation: _TypeAlias = Reservation  # noqa: Y015

@_typing.final
class Limit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DURATION_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    duration: _builtins.int
    data: _builtins.int
    def __init__(
        self,
        *,
        duration: _builtins.int = ...,
        data: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "duration", b"duration"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Limit: _TypeAlias = Limit  # noqa: Y015

@_typing.final
class Status(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Code:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Status._Code.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        OK: Status._Code.ValueType  # 0
        RESERVATION_REFUSED: Status._Code.ValueType  # 100
        RESOURCE_LIMIT_EXCEEDED: Status._Code.ValueType  # 101
        PERMISSION_DENIED: Status._Code.ValueType  # 102
        CONNECTION_FAILED: Status._Code.ValueType  # 200
        DIAL_REFUSED: Status._Code.ValueType  # 201
        NO_RESERVATION: Status._Code.ValueType  # 204
        STOP_FAILED: Status._Code.ValueType  # 300
        MALFORMED_MESSAGE: Status._Code.ValueType  # 400

    class Code(_Code, metaclass=_CodeEnumTypeWrapper): ...
    OK: Status.Code.ValueType  # 0
    RESERVATION_REFUSED: Status.Code.ValueType  # 100
    RESOURCE_LIMIT_EXCEEDED: Status.Code.ValueType  # 101
    PERMISSION_DENIED: Status.Code.ValueType  # 102
    CONNECTION_FAILED: Status.Code.ValueType  # 200
    DIAL_REFUSED: Status.Code.ValueType  # 201
    NO_RESERVATION: Status.Code.ValueType  # 204
    STOP_FAILED: Status.Code.ValueType  # 300
    MALFORMED_MESSAGE: Status.Code.ValueType  # 400

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    code: Global___Status.Code.ValueType
    message: _builtins.str
    def __init__(
        self,
        *,
        code: Global___Status.Code.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Status: _TypeAlias = Status  # noqa: Y015
