# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libp2p/record/pb/record.proto

from google.protobuf import message as _message
from typing import Optional


class Record(_message.Message):
    """Protobuf Record message"""
    __slots__ = ['key', 'value', 'author', 'signature', 'timeReceived']
    
    def __init__(
        self,
        key: bytes = b"",
        value: bytes = b"",
        author: str = "",
        signature: bytes = b"",
        timeReceived: str = "",
    ) -> None:
        super().__init__()
        self.key = key
        self.value = value  
        self.author = author
        self.signature = signature
        self.timeReceived = timeReceived
